### ISSUE TITLE
main.go文件呢?大佬

### ISSUE THREAD

**Issue by Charles-Hello** [afraidjpg/rbq-go#2]
我想问一下，如果收到信息，如何执行插件的逻辑？能提供联系方式吗？有个问题想问问！

**Comment by Charles-Hello** [comment]
AddPlugin这个函数没有调用没有搞懂？大佬有更全的文档吗？

**Comment by Charles-Hello** [comment]
有偿也可！

**Comment by afraidjpg** [comment]
@Charles-Hello 不要意思，时隔这么久才回复（一直没看到！！github竟然没给我通知！），竟然真的有人尝试使用，确实是受宠若惊，这半年一直在摸鱼状态下进度十分缓慢，现在的main分支的内容会被我完全废弃（几乎重写了）。这两天应该会并一个何用的版本到main附带一个简单的文档和example
